// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbcmvlhsdbjjixgqhwhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiY212bGhzZGJqaml4Z3Fod2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjUyODUsImV4cCI6MjA2MjA0MTI4NX0.m-c3W2zhrZcrCbse6fx8NN2KzNcmdQTvTWPl2W65dHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);